# environment.yml
name: research_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - jupyterlab
  - pip
  - pip:
      - notebook-as-pdf # For PDF exports
